version: '3.8'

services:
  # --- Backend Java Spring ---
  spring-backend:
    build: ./SpringBootServer
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/filmdata
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres-db
    networks:
      - cinema-network

  # --- Express Service ---
  express-service:
    build: ./ExpressServer
    ports:
      - "3001:3001"
    environment:
      - DB_URL=mongodb://mongo-db:27017/film_db
    depends_on:
      - mongo-db
    networks:
      - cinema-network

  # --- Central Server ---
  central-server:
    build: ./CentralServer
    ports:
      - "3000:3000"
    networks:
      - cinema-network

  # --- Databases ---
  postgres-db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=filmdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    networks:
      - cinema-network

  mongo-db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    networks:
      - cinema-network

networks:
  cinema-network:
    driver: bridge